server:
  port: 8008
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 200265
    url: jdbc:mysql://localhost:3306/guli
  application:
    name: service-order
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.134.128:8848
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true