server:
  port: 8002
spring:
  application:
    name: service-oss
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.134.128:8848

aliyun:
    oss:
      file:
        endpoint: 
        keyid: 
        keysecret: 
        bucketname: 